## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW1_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [1]:
import pandas as pd
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [2]:
# Type your solution here
# Q1-1
myDataSet = pd.DataFrame(data)
print(myDataSet)



     name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1


In [3]:
#Q1-2
myDataSet[((myDataSet["job"]=="psychologist")| (myDataSet["job"]=="teacher"))& (myDataSet["num_cars"]>myDataSet["family_size"])]


name           job  family_size  num_cars
5  Lisa  psychologist            3         4

In [ ]:
#Q1-3
myDataSet[(myDataSet["family_size"]<=2)&(myDataSet["num_cars"]>=1)]

name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1

In [4]:
#Q1-4
count = 0
new_list = []
for x in range(0, len(myDataSet["job"])):
  if myDataSet["job"][x] not in new_list:
    new_list.append(myDataSet["job"][x])
    count+=1
print(count)

4


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [5]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [12]:
# Type your solution here
if len(fruit) == len(weights):
  data = {"Fruit":fruit, "Weight":weights}
  myDataList = pd.DataFrame(data)
  print("DataFrame")
  print(myDataList)
mean = myDataList.groupby(fruit).mean()
print("Mean of Weights of Fruit")
print(mean)


DataFrame
    Fruit  Weight
0  banana     1.0
1   apple     2.0
2  carrot     3.0
3  banana     4.0
4  carrot     5.0
5   apple     6.0
6   apple     7.0
7  banana     8.0
8  banana     9.0
9   apple    10.0
Mean of Weights of Fruit
        Weight
apple     6.25
banana    5.50
carrot    4.00


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [15]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [22]:
# Type your solution here
#Q3-1
print(course_name)
sorted_course_name = np.argsort(course_name)
print(sorted_course_name)

['Python' 'JS' 'examples' 'PHP' 'html']
[1 3 0 2 4]


In [17]:
#Q3-2
course_name_check = np.char.startswith(course_name, "P")
print(course_name_check)


[ True False False  True False]


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [24]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [25]:
# Type your solution here
#Q4-1
new_array = student_id.copy()
print("Reversed array:", new_array[::-1])
print("Original array:", student_id)

Reversed array: [4532 5241 1682 1671 6230 5202 1023]
Original array: [1023 5202 6230 1671 1682 5241 4532]


In [26]:
#Q4-2
new_array = np.argsort(student_id)
sorted = student_id[new_array]
x = 3
largest = sorted[-x:]
print(largest)

[5202 5241 6230]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
# Type your solution here

# Hint: you can use arange to start off
import numpy as np
num = np.arange(1, 100)
mult = num[(num%3==0)|(num%5==0)]
print(mult.sum())

2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [27]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [28]:
# Type your solution here
#Q6-1
arr_1 = np.copy(arr)
arr[:, [1,2]]= arr[:, [2,1]]
print(arr)

[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]


In [29]:
#Q6-2
# I made a copy so I can show just the switched rows and the results from the previous question wouldn't show
arr_1[[0,1], :] = arr_1[[1,0], :]
print(arr_1)

[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
